### ISSUE TITLE
Linking between projects and a couple of ideas

### ISSUE THREAD

**Issue by alprinias** [Terricide/ReVision#3]
Hi Mark, 

I don't really know what you mean by linking files between projects, and the link you provide in the ReadMe takes me to a gitter.im something like a chat room... What am I missing?

May I suggest a restructure of the ReVision.Forms project? I believe that putting the .cs files in folders will make it all much cleaner and easier to understand. Folders like "Controls", "Helpers", "Enumerations", "Base Classes" etc, you know your code better! 

Finally, I believe it would help a lot to write a short description of the way it all works. What each project does, what one has to do to include a new control, etc. This way it would be easier for other people to jump in and help in porting more controls. 

All the best,
Alex

**Comment by Terricide** [comment]
"I don't really know what you mean by linking files between projects, and the link you provide in the ReadMe takes me to a gitter.im something like a chat room... What am I missing?"

It means that we have all the code in the WindowsFormsLib so that we can use the designer. Then instead of copying for example "MainForm.cs, MainForm.resx and MainForm.designer.cs" we create a link to those files in the WebSite project.

You don't have to do this. The only purpose to leverage the designer.

**Comment by Terricide** [comment]
"May I suggest a restructure of the ReVision.Forms project? I believe that putting the .cs files in folders will make it all much cleaner and easier to understand. Folders like "Controls", "Helpers", "Enumerations", "Base Classes" etc, you know your code better!"

Yeah that sounds great to me. It should only take a few minutes. Also feel free to submit any pull requests you want and I can get them in.

**Comment by Terricide** [comment]
"Finally, I believe it would help a lot to write a short description of the way it all works. What each project does, what one has to do to include a new control, etc. This way it would be easier for other people to jump in and help in porting more controls."

Okay I will try and do it this weekend. Maybe do a video with commentary first and then write it all out.

**Comment by Terricide** [comment]
I've reorganized the Revision library into folders and fixed the nuget package references back to 4.5

**Comment by Terricide** [comment]
I've created a video of adding the MaskedTextbox control

https://www.youtube.com/watch?v=PwvnmJ2JEic
