### ISSUE TITLE
Various Browsers

### ISSUE THREAD

**Issue by alprinias** [Terricide/ReVision#5]
Hi,

I was testing in various browsers, here is the first result:

Chrome OK
Internet Explorer 11 OK
Opera OK
Microsoft Edge OK, the transition between tabs is instant, not "fading" as in Chrome
Firefox Does not show correctly, most part of the page is missing
Safari does not show at all, probably websockets problem, gives "disconnected" error

Alex

**Comment by Terricide** [comment]
Can you try Firefox again? I just tested it and it seems to be working

**Comment by alprinias** [comment]
Hi, 
No, my FireFox refuses to show most of the page, all text is missing (next to radio buttons, labels, button caption etc), whereas the actual controls are there. My Firefox version is 43.0.1.

A, but wait, let me check for updates... 

And yes, with 45.1 it works... Who knows what made the difference, let's hope that it will work with 46.1 too !
Alex
